stages:
  - build
  - test

image: maven:latest

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  JASYPT: "-Djasypt.encryptor.password=${JASYPT_SECRET}"
  DOCKER_HUB_ID: pedsf1968

build_job:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

test_job:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS $JASYPT test -Pdevelopment

