language: java
sudo: true
dist: trusty

# use Java 8
jdk: openjdk8

before_install:
  - chmod +x mvnw

jobs:
  include:
    - stage: test
      script: ./mvnw clean test -P test > ./mvn-test.log
    - stage: sonar
      script: ./mvnw verify sonar:sonar -P test > ./mvn-verify.log

cache:
  directories:
    - $HOME/.m2

notifications:
  email: pe.dsf@free.fr
